sudo: required
services:
  - docker

before_install:
  - docker build -t my-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true my-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-192448963779"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"